### ISSUE TITLE
Crashing on right-click for guilds

### ISSUE THREAD

**Issue by RzR332Guyver** [YofukashiNo/ShowHiddenChannels#1]
I have tried all of my plugins and this is the one that causes my Discord to "crash" whenever I right-click on *any* guild/server and sometimes clicking on user-settings.
![image](https://user-images.githubusercontent.com/1342961/227398466-503d4218-b380-48ae-8415-f23cc69af44a.png)
![image](https://user-images.githubusercontent.com/1342961/227398482-0c2dd1b3-5b46-4e22-9647-61a7c781e3cc.png)
(Hope those images actually upload.. still unsure how to actually do that when it comes to Github.)

**Comment by yofukashino** [comment]
Any error when the plugin starts?
Update the plugins and let me know

**Comment by RzR332Guyver** [comment]
Only this really:
![image](https://user-images.githubusercontent.com/1342961/227427943-911c2615-66df-49d7-a429-da5899606d89.png)

Other than that it seems to work just fine.

**Comment by yofukashino** [comment]
Wait you are getting this error too. Okay idk what the fix is yet. Let's talk in replugged server

**Comment by yofukashino** [comment]
should be fixed with latest replugged and plugin update
