### ISSUE TITLE
[Replugged] update request

### ISSUE THREAD

**Issue by ZeeWanderer** [YofukashiNo/ShowHiddenChannels#14]
Replugged store still uses `1.2.0` (the same version is installed via the install link); as of the latest discord/replugged update, it stopped working correctly. An update is in order and my cursory perusal of the plugins dev guide suggests that as an existing developer you should request an update to the store in [#addon-reviews](https://discord.com/channels/1000926524452647132/1106817903967338496). Maybe I misunderstood something, in which case sorry for bothering you.

**Comment by yofukashino** [comment]
https://github.com/YofukashiNo/ShowHiddenChannels/issues/10

because of this, it hasn't been updated on the store yet.

**Comment by ZeeWanderer** [comment]
Well, the the current store version no longer works i.e. hidden channels are not shown so maybe there is some previous version that is not blocked by that issue but is in working order that can be pushed to the store.

At least as I now found out the plugin updater is not automatic (I was under the impression that it was) so I can keep the manual install. In which case close the issue if you want

**Comment by yofukashino** [comment]
just wait for the pr and then the update on store will happen
