### ISSUE TITLE
plugin no longer works with latest discord update and replug build

### ISSUE THREAD

**Issue by SgtSlaughter16** [YofukashiNo/ShowHiddenChannels#15]
plugin no longer works with latest discord update and replug build. no error on UI thrown just hidden channels no longer show.

replugged v4.8.0, and SHC v 1.4.0

**Comment by yofukashino** [comment]
probably https://github.com/YofukashiNo/ShowHiddenChannels/issues/10

**Comment by SgtSlaughter16** [comment]
sure its #10? it was working fine prior to the big base discord update and they noted many apps will need to make changes to work based on the changes replugged had to do in order to get it to work with discord again

**Comment by yofukashino** [comment]
> sure its #10? it was working fine prior to the big base discord update and they noted many apps will need to make changes to work based on the changes replugged had to do in order to get it to work with discord again

nah but it was fixed in latest version anyways. also replugged broken again
