### ISSUE TITLE
Hide Categories When All Channels in Category Are Hidden

### ISSUE THREAD

**Issue by aaronliu0130** [YofukashiNo/ShowHiddenChannels#2]
![image](https://user-images.githubusercontent.com/11874211/231316209-e38c404b-e562-44c2-9a46-fde7f78d25b0.png)
The Browse Channels onboarding feature

**Comment by yofukashino** [comment]
Disable show empty catogary option in plugins setting to avoid that

**Comment by aaronliu0130** [comment]
Oh, should that be disabled by default?

**Comment by yofukashino** [comment]
Nah it's enabled by default

**Comment by aaronliu0130** [comment]
Also, are there plans to support the "This is a hidden channel" view in side-by-side mode?
![image](https://user-images.githubusercontent.com/11874211/231316805-404010dc-b5c1-453d-9405-c6a328bf88e2.png)

**Comment by aaronliu0130** [comment]
> Nah it's enabled by default

ik I was thinking that maybe it should be the default

**Comment by yofukashino** [comment]
> > Nah it's enabled by default
> 
> ik I was thinking that maybe it should be the default

nope.

**Comment by yofukashino** [comment]
> Also, are there plans to support the "This is a hidden channel" view in side-by-side mode? ![image](https://user-images.githubusercontent.com/11874211/231316805-404010dc-b5c1-453d-9405-c6a328bf88e2.png)

added in https://github.com/Tharki-God/ShowHiddenChannels/commit/09a4afc3c21500e945f15ce26ad3ccc8d7ade87d
