### ISSUE TITLE
Cant leave servers

### ISSUE THREAD

**Issue by Diyagi** [YofukashiNo/ShowHiddenChannels#3]
An error is occurring when trying to leave an discord server, after disabling this plugin, the error goes away.

![image](https://user-images.githubusercontent.com/9062212/231344388-8db8e1e0-db62-42ce-aa63-073fa20c6f4a.png)

**Comment by yofukashino** [comment]
fixed in https://github.com/Tharki-God/ShowHiddenChannels/commit/09a4afc3c21500e945f15ce26ad3ccc8d7ade87d
