### ISSUE TITLE
Not reliably showing hidden channels anymore

### ISSUE THREAD

**Issue by RzR332Guyver** [YofukashiNo/ShowHiddenChannels#4]
Seems random but hidden-categories that have channels in them will suddenly no-longer have any channels in them, despite the category still existing.
These categories will disappear as well if you disable "Show empty categories" option.
![image](https://user-images.githubusercontent.com/1342961/232279886-79b71ad6-93db-4fcd-9a39-a0294de5f195.png)
For example the first image is the Larian Studios server before a restart.
![image](https://user-images.githubusercontent.com/1342961/232279902-556a0d32-13f0-4af9-bf92-cd6a9658398d.png)
And the second image is after a restart.

**Comment by yofukashino** [comment]
That's because of discord's new feature where you can select which channels you want to see.
Just right click on server and make sure show all channels is checked

**Comment by yofukashino** [comment]
closing this issue coz of no response
