### ISSUE TITLE
Broken on latest Discord

### ISSUE THREAD

**Issue by thewilloftheshadow** [YofukashiNo/ShowHiddenChannels#6]
The plugin is showing a large black lock in the channel list instead of the hidden channels. It also is not clickable, but hovering shows the Hidden Channel tooltip

**Comment by yofukashino** [comment]
will push the fix when I join back replugged in some days. I have already made a fix

**Comment by aaronliu0130** [comment]
![image](https://github.com/Tharki-God/ShowHiddenChannels/assets/11874211/f5ce53c3-e22c-497d-a75e-e6dd36c4bc54)
me have funny screenshot

**Comment by thewilloftheshadow** [comment]
> will push the fix when I join back replugged in some days. I have already made a fix

Can you go ahead and push it to Github so I can install it manually?

**Comment by RobertK0** [comment]
@thewilloftheshadow @aaronliu0130 you can make it work by going to plugin settings and setting hidden channel icon to none, or if you want a functioning icon and can build your own plugin, go to `src/patches/Visuals.tsx` and replace `patchChannelBrowerLockIcon` function with this .
```
export const patchChannelBrowerLockIcon = () => {
  const FunctionKey = webpack.getFunctionKeyBySource(ChannelItem, ".locked") as string;
  PluginInjector.after(
    ChannelItem,
    FunctionKey,
    (
      [props]: [{ channel: Types.Channel; guild: Types.Guild; className?: string }],
      res: Types.ReactElement,
    ) => res,
  );
};
```

For whatever reason the tooltip renders twice and the second time it overwrites the entire chat name element, not sure why though, original creator probably has a better solution, I've just looked into it a bit and found this.

**Comment by yofukashino** [comment]
closing this as the update had been pushed yesterday
